"""add platform_app_credentials

Revision ID: 0554b25d9c17
Revises: e50963092bf7
Create Date: 2026-07-23 23:03:12.166465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.services.crypto

# revision identifiers, used by Alembic.
revision: str = '0554b25d9c17'
down_revision: Union[str, Sequence[str], None] = 'e50963092bf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_app_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.Enum('etsy', 'ebay', 'shopify', name='listing_platform', native_enum=False), nullable=False),
    sa.Column('environment', sa.Enum('production', 'sandbox', name='platform_environment', native_enum=False), nullable=False),
    sa.Column('client_id', sa.String(), nullable=True),
    sa.Column('client_secret', app.services.crypto.EncryptedString(), nullable=True),
    sa.Column('public_base_url', sa.String(), nullable=True),
    sa.Column('ru_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'environment', name='uq_platform_app_credentials_platform_env')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('platform_app_credentials')
    # ### end Alembic commands ###
