"""add index on orders order_placed_at

Revision ID: 170896b4ae84
Revises: 4cbd5b0940cd
Create Date: 2026-07-25 21:36:56.442894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '170896b4ae84'
down_revision: Union[str, Sequence[str], None] = '4cbd5b0940cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_orders_order_placed_at_id', 'orders', ['order_placed_at', 'id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_orders_order_placed_at_id', table_name='orders')
    # ### end Alembic commands ###
