"""add platform_connection auto-sync settings

Revision ID: 41eaa7553763
Revises: 0554b25d9c17
Create Date: 2026-07-23 23:12:57.488336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41eaa7553763'
down_revision: Union[str, Sequence[str], None] = '0554b25d9c17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'platform_connections',
        sa.Column('auto_sync_enabled', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    )
    op.add_column(
        'platform_connections',
        sa.Column('sync_interval_minutes', sa.Integer(), server_default=sa.text('15'), nullable=False),
    )
    op.add_column(
        'platform_connections',
        sa.Column('consecutive_auth_failures', sa.Integer(), server_default=sa.text('0'), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('platform_connections', 'consecutive_auth_failures')
    op.drop_column('platform_connections', 'sync_interval_minutes')
    op.drop_column('platform_connections', 'auto_sync_enabled')
    # ### end Alembic commands ###
