"""add platform_listing_pushes

Revision ID: 789d0a3995db
Revises: 41eaa7553763
Create Date: 2026-07-23 23:26:01.016076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '789d0a3995db'
down_revision: Union[str, Sequence[str], None] = '41eaa7553763'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_listing_pushes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('variant_id', sa.Integer(), nullable=True),
    sa.Column('platform', sa.Enum('etsy', 'ebay', 'shopify', name='listing_platform', native_enum=False), nullable=False),
    sa.Column('attempted_qty', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('success', 'error', name='listing_push_status', native_enum=False), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('attempted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('platform_listing_pushes')
    # ### end Alembic commands ###
