"""add platform_connection environment

Revision ID: ccf4a0f4bd8f
Revises: 789d0a3995db
Create Date: 2026-07-24 00:07:50.725030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccf4a0f4bd8f'
down_revision: Union[str, Sequence[str], None] = '789d0a3995db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'platform_connections',
        sa.Column(
            'environment',
            sa.Enum('production', 'sandbox', name='platform_environment', native_enum=False),
            server_default='production',
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('platform_connections', 'environment')
    # ### end Alembic commands ###
