"""add order_line_returns and pending_marketplace_cancellation

Revision ID: dad84c4b7c9a
Revises: ccf4a0f4bd8f
Create Date: 2026-07-24 08:57:40.412609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dad84c4b7c9a'
down_revision: Union[str, Sequence[str], None] = 'ccf4a0f4bd8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_line_returns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_line_id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.Enum('product', 'kitting', name='return_scope', native_enum=False), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=True),
    sa.Column('qty', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('disposition', sa.Enum('scrap', 'return_to_stock', name='return_disposition', native_enum=False), nullable=False),
    sa.Column('source', sa.Enum('cancel_before_ship', 'return_after_ship', name='return_source', native_enum=False), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_line_id'], ['order_lines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(
        'orders',
        sa.Column('pending_marketplace_cancellation', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'pending_marketplace_cancellation')
    op.drop_table('order_line_returns')
    # ### end Alembic commands ###
