"""baseline

Revision ID: e50963092bf7
Revises: 
Create Date: 2026-07-23 14:12:32.067922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.services.crypto

# revision identifiers, used by Alembic.
revision: str = 'e50963092bf7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('general_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('default_currency', sa.Enum('GBP', 'USD', 'EUR', name='currency_code', native_enum=False), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('manufacturers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('website_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('margin_fee_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fee_source', sa.Enum('manual', 'etsy', 'ebay', name='margin_fee_source', native_enum=False), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('material_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('platform_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.Enum('etsy', 'ebay', 'shopify', name='listing_platform', native_enum=False), nullable=False),
    sa.Column('access_token', app.services.crypto.EncryptedString(), nullable=True),
    sa.Column('refresh_token', app.services.crypto.EncryptedString(), nullable=True),
    sa.Column('access_token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scopes', sa.String(), nullable=True),
    sa.Column('external_account_id', sa.String(), nullable=True),
    sa.Column('shop_name', sa.String(), nullable=True),
    sa.Column('shop_icon_path', sa.String(), nullable=True),
    sa.Column('sync_start_date', sa.Date(), nullable=True),
    sa.Column('last_orders_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_refreshed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform')
    )
    op.create_table('platform_fee_components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.Enum('etsy', 'ebay', 'shopify', name='listing_platform', native_enum=False), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('basis', sa.Enum('sale_price', 'sale_price_plus_shipping', 'fees_subtotal', name='fee_basis', native_enum=False), nullable=False),
    sa.Column('rate_percent', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('fixed_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('rate_percent IS NOT NULL OR fixed_amount IS NOT NULL', name='ck_platform_fee_components_has_value'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('platform_sync_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.Enum('etsy', 'ebay', 'shopify', name='listing_platform', native_enum=False), nullable=False),
    sa.Column('mode', sa.Enum('preview', 'commit', name='sync_run_mode', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('success', 'error', name='sync_run_status', native_enum=False), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_count', sa.Integer(), nullable=False),
    sa.Column('new_count', sa.Integer(), nullable=False),
    sa.Column('needs_mapping_count', sa.Integer(), nullable=False),
    sa.Column('shipped_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shipping_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cost_etsy', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cost_ebay', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cost_manual', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('cost_ebay >= 0', name='ck_shipping_profiles_cost_ebay_nonneg'),
    sa.CheckConstraint('cost_etsy >= 0', name='ck_shipping_profiles_cost_etsy_nonneg'),
    sa.CheckConstraint('cost_manual >= 0', name='ck_shipping_profiles_cost_manual_nonneg'),
    sa.CheckConstraint('price >= 0', name='ck_shipping_profiles_price_nonneg'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('website_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.Enum('filament', 'resin', 'pigment', 'hardware', 'packaging', 'blanks', 'other', name='material_category', native_enum=False), nullable=False),
    sa.Column('unit', sa.Enum('g', 'ml', 'each', name='material_unit', native_enum=False), nullable=False),
    sa.Column('current_qty', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('allocated_qty', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('reorder_threshold', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('avg_unit_cost', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('colour', sa.String(), nullable=True),
    sa.Column('material_type_id', sa.Integer(), nullable=True),
    sa.Column('barcode', sa.String(), nullable=True),
    sa.Column('manufacturer_id', sa.Integer(), nullable=True),
    sa.Column('default_supplier_id', sa.Integer(), nullable=True),
    sa.Column('typical_reorder_qty', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('product_url', sa.String(), nullable=True),
    sa.Column('image_path', sa.String(), nullable=True),
    sa.Column('image_original_filename', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('allocated_qty >= 0 AND allocated_qty <= current_qty', name='ck_materials_allocated_qty_range'),
    sa.CheckConstraint('avg_unit_cost >= 0', name='ck_materials_avg_unit_cost_nonneg'),
    sa.CheckConstraint('current_qty >= 0', name='ck_materials_current_qty_nonneg'),
    sa.CheckConstraint('reorder_threshold >= 0', name='ck_materials_reorder_threshold_nonneg'),
    sa.ForeignKeyConstraint(['default_supplier_id'], ['suppliers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['material_type_id'], ['material_types.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.Enum('etsy', 'ebay', 'shopify', name='listing_platform', native_enum=False), nullable=True),
    sa.Column('external_order_id', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'allocated', 'shipped', 'cancelled', name='order_status', native_enum=False), nullable=False),
    sa.Column('buyer_name', sa.String(), nullable=True),
    sa.Column('buyer_note', sa.String(), nullable=True),
    sa.Column('order_placed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('shipped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('grand_total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('shipping_charged', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tax_charged', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('vat_charged', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('refunded_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('payment_fees', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('payment_net', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('payment_status', sa.String(), nullable=True),
    sa.Column('financials_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_issue', sa.String(), nullable=True),
    sa.Column('shipping_profile_id', sa.Integer(), nullable=True),
    sa.Column('shipping_cost_snapshot', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['shipping_profile_id'], ['shipping_profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'external_order_id', name='uq_orders_platform_external_id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sku', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('barcode', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('current_stock', sa.Integer(), nullable=False),
    sa.Column('allocated_qty', sa.Integer(), nullable=False),
    sa.Column('is_bundle', sa.Boolean(), nullable=False),
    sa.Column('variant_attribute1_name', sa.String(), nullable=True),
    sa.Column('variant_attribute2_name', sa.String(), nullable=True),
    sa.Column('variant_attribute3_name', sa.String(), nullable=True),
    sa.Column('sale_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('shipping_profile_id', sa.Integer(), nullable=True),
    sa.Column('platform_fee_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('pricing_mode', sa.Enum('product', 'variable', 'line', name='pricing_mode', native_enum=False), nullable=False),
    sa.Column('pricing_variable_attribute', sa.Integer(), nullable=True),
    sa.Column('platform_ceiling_qty', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('allocated_qty >= 0 AND allocated_qty <= current_stock', name='ck_products_allocated_qty_range'),
    sa.CheckConstraint('current_stock >= 0', name='ck_products_current_stock_nonneg'),
    sa.CheckConstraint('platform_ceiling_qty IS NULL OR platform_ceiling_qty >= 0', name='ck_products_platform_ceiling_qty_nonneg'),
    sa.CheckConstraint('platform_fee_percent >= 0 AND platform_fee_percent <= 100', name='ck_products_platform_fee_percent_range'),
    sa.CheckConstraint('pricing_variable_attribute IS NULL OR pricing_variable_attribute BETWEEN 1 AND 3', name='ck_products_pricing_variable_attribute_range'),
    sa.CheckConstraint('sale_price >= 0', name='ck_products_sale_price_nonneg'),
    sa.ForeignKeyConstraint(['shipping_profile_id'], ['shipping_profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    op.create_table('purchases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('order_date', sa.Date(), server_default=sa.text('(CURRENT_DATE)'), nullable=False),
    sa.Column('status', sa.Enum('ordered', 'received', name='purchase_status', native_enum=False), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('material_purchases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('qty > 0', name='ck_material_purchases_qty_positive'),
    sa.CheckConstraint('total_cost >= 0', name='ck_material_purchases_total_cost_nonneg'),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_kitting_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('reserved_qty', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('consumed_qty', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('consumed_qty >= 0', name='ck_order_kitting_allocations_consumed_qty_nonneg'),
    sa.CheckConstraint('reserved_qty >= 0', name='ck_order_kitting_allocations_reserved_qty_nonneg'),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', 'material_id', name='uq_order_kitting_allocations_order_material')
    )
    op.create_table('order_kitting_overrides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('qty_required', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('replaces_material_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('qty_required >= 0', name='ck_order_kitting_overrides_qty_required_nonneg'),
    sa.CheckConstraint('replaces_material_id IS NULL OR replaces_material_id != material_id', name='ck_order_kitting_overrides_no_self_substitution'),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['replaces_material_id'], ['materials.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', 'material_id', name='uq_order_kitting_overrides_order_material')
    )
    op.create_table('product_bundle_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bundle_product_id', sa.Integer(), nullable=False),
    sa.Column('component_product_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.CheckConstraint('bundle_product_id != component_product_id', name='ck_product_bundle_items_no_self_reference'),
    sa.CheckConstraint('qty > 0', name='ck_product_bundle_items_qty_positive'),
    sa.ForeignKeyConstraint(['bundle_product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['component_product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bundle_product_id', 'component_product_id', name='uq_product_bundle_items_pair')
    )
    op.create_table('product_kitting_materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('qty_required', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.CheckConstraint('qty_required > 0', name='ck_product_kitting_materials_qty_required_positive'),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'material_id', name='uq_product_kitting_materials_product_material')
    )
    op.create_table('product_materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('qty_required', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.CheckConstraint('qty_required > 0', name='ck_product_materials_qty_required_positive'),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'material_id', name='uq_product_materials_product_material')
    )
    op.create_table('product_price_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('cost_per_unit', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('sale_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('margin_percent', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('variant_name', sa.String(), nullable=False),
    sa.Column('sku_suffix', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('current_stock', sa.Integer(), nullable=False),
    sa.Column('allocated_qty', sa.Integer(), nullable=False),
    sa.Column('attribute1_value', sa.String(), nullable=True),
    sa.Column('attribute2_value', sa.String(), nullable=True),
    sa.Column('attribute3_value', sa.String(), nullable=True),
    sa.Column('sale_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('shipping_profile_id', sa.Integer(), nullable=True),
    sa.Column('platform_fee_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('allocated_qty >= 0 AND allocated_qty <= current_stock', name='ck_product_variants_allocated_qty_range'),
    sa.CheckConstraint('current_stock >= 0', name='ck_product_variants_current_stock_nonneg'),
    sa.CheckConstraint('platform_fee_percent >= 0 AND platform_fee_percent <= 100', name='ck_product_variants_platform_fee_percent_range'),
    sa.CheckConstraint('sale_price >= 0', name='ck_product_variants_sale_price_nonneg'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shipping_profile_id'], ['shipping_profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'attribute1_value', 'attribute2_value', 'attribute3_value', name='uq_product_variants_attribute_combo'),
    sa.UniqueConstraint('product_id', 'variant_name', name='uq_product_variants_product_name')
    )
    op.create_table('builds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=True),
    sa.Column('qty_built', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('built_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('qty_built > 0', name='ck_builds_qty_built_positive'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=True),
    sa.Column('platform', sa.Enum('etsy', 'ebay', 'shopify', name='listing_platform', native_enum=False), nullable=False),
    sa.Column('external_listing_id', sa.String(), nullable=True),
    sa.Column('ceiling_qty', sa.Integer(), nullable=True),
    sa.Column('last_synced_qty', sa.Integer(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('external_title', sa.String(), nullable=True),
    sa.Column('external_variation', sa.String(), nullable=True),
    sa.Column('external_state', sa.String(), nullable=True),
    sa.Column('external_quantity', sa.Integer(), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        'uq_listings_product_variant_platform',
        'listings',
        ['product_id', sa.text('coalesce(variant_id, -1)'), 'platform'],
        unique=True,
    )
    op.create_table('material_adjustments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.Enum('adjust', 'set', name='material_adjustment_mode', native_enum=False), nullable=False),
    sa.Column('qty_delta', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('target_qty', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('variant_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("qty_delta != 0 OR mode = 'set'", name='ck_material_adjustments_qty_delta_nonzero'),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('variant_id', sa.Integer(), nullable=True),
    sa.Column('ordered_qty', sa.Integer(), nullable=False),
    sa.Column('allocated_qty', sa.Integer(), nullable=False),
    sa.Column('shipped_qty', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('external_line_id', sa.String(), nullable=True),
    sa.Column('sku', sa.String(), nullable=True),
    sa.Column('needs_mapping', sa.Boolean(), nullable=False),
    sa.Column('cost_per_unit_snapshot', sa.Numeric(precision=14, scale=6), nullable=True),
    sa.Column('kitting_cost_per_unit_snapshot', sa.Numeric(precision=14, scale=6), nullable=True),
    sa.CheckConstraint('allocated_qty >= 0 AND allocated_qty <= ordered_qty', name='ck_order_lines_allocated_qty_range'),
    sa.CheckConstraint('ordered_qty > 0', name='ck_order_lines_ordered_qty_positive'),
    sa.CheckConstraint('shipped_qty >= 0 AND shipped_qty <= allocated_qty', name='ck_order_lines_shipped_qty_range'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=True),
    sa.Column('asset_type', sa.Enum('main_image', 'listing_image', 'step', 'threemf', 'gcode', name='asset_type', native_enum=False), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_variant_kitting_materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('qty_required', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('replaces_material_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('qty_required >= 0', name='ck_product_variant_kitting_materials_qty_required_nonneg'),
    sa.CheckConstraint('replaces_material_id IS NULL OR replaces_material_id != material_id', name='ck_product_variant_kitting_materials_no_self_substitution'),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['replaces_material_id'], ['materials.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('variant_id', 'material_id', name='uq_product_variant_kitting_materials_variant_material')
    )
    op.create_table('product_variant_materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('qty_required', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('replaces_material_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('qty_required >= 0', name='ck_product_variant_materials_qty_required_nonneg'),
    sa.CheckConstraint('replaces_material_id IS NULL OR replaces_material_id != material_id', name='ck_product_variant_materials_no_self_substitution'),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['replaces_material_id'], ['materials.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('variant_id', 'material_id', name='uq_product_variant_materials_variant_material')
    )
    op.create_table('sku_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.Enum('etsy', 'ebay', 'shopify', name='listing_platform', native_enum=False), nullable=False),
    sa.Column('external_sku', sa.String(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'external_sku', name='uq_sku_aliases_platform_external_sku')
    )
    op.create_table('stock_adjustments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=True),
    sa.Column('mode', sa.Enum('adjust', 'set', name='stock_adjustment_mode', native_enum=False), nullable=False),
    sa.Column('qty_delta', sa.Integer(), nullable=False),
    sa.Column('target_qty', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("qty_delta != 0 OR mode = 'set'", name='ck_stock_adjustments_qty_delta_nonzero'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('allocation_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_line_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('variant_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.Enum('allocate', 'deallocate', 'ship', 'auto_allocate', name='allocation_event_type', native_enum=False), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['order_line_id'], ['order_lines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('allocation_events')
    op.drop_table('stock_adjustments')
    op.drop_table('sku_aliases')
    op.drop_table('product_variant_materials')
    op.drop_table('product_variant_kitting_materials')
    op.drop_table('product_assets')
    op.drop_table('order_lines')
    op.drop_table('material_adjustments')
    op.drop_index('uq_listings_product_variant_platform', table_name='listings')
    op.drop_table('listings')
    op.drop_table('builds')
    op.drop_table('product_variants')
    op.drop_table('product_price_snapshots')
    op.drop_table('product_materials')
    op.drop_table('product_kitting_materials')
    op.drop_table('product_bundle_items')
    op.drop_table('order_kitting_overrides')
    op.drop_table('order_kitting_allocations')
    op.drop_table('material_purchases')
    op.drop_table('purchases')
    op.drop_table('products')
    op.drop_table('orders')
    op.drop_table('materials')
    op.drop_table('suppliers')
    op.drop_table('shipping_profiles')
    op.drop_table('platform_sync_runs')
    op.drop_table('platform_fee_components')
    op.drop_table('platform_connections')
    op.drop_table('material_types')
    op.drop_table('margin_fee_config')
    op.drop_table('manufacturers')
    op.drop_table('general_settings')
    # ### end Alembic commands ###
