/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuppliersIndexRouteImport } from './routes/suppliers/index'
import { Route as PurchasesIndexRouteImport } from './routes/purchases/index'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as OrdersIndexRouteImport } from './routes/orders/index'
import { Route as MaterialsIndexRouteImport } from './routes/materials/index'
import { Route as MaterialTypesIndexRouteImport } from './routes/material-types/index'
import { Route as ManufacturersIndexRouteImport } from './routes/manufacturers/index'
import { Route as PurchasesNewRouteImport } from './routes/purchases/new'
import { Route as PurchasesPurchaseIdRouteImport } from './routes/purchases/$purchaseId'
import { Route as ProductsProductIdRouteImport } from './routes/products/$productId'
import { Route as ProductLabelProductIdRouteImport } from './routes/product-label.$productId'
import { Route as OrdersNewRouteImport } from './routes/orders/new'
import { Route as OrdersOrderIdRouteImport } from './routes/orders/$orderId'
import { Route as MaterialsMaterialIdRouteImport } from './routes/materials/$materialId'
import { Route as MaterialLabelMaterialIdRouteImport } from './routes/material-label.$materialId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersIndexRoute = SuppliersIndexRouteImport.update({
  id: '/suppliers/',
  path: '/suppliers/',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasesIndexRoute = PurchasesIndexRouteImport.update({
  id: '/purchases/',
  path: '/purchases/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialsIndexRoute = MaterialsIndexRouteImport.update({
  id: '/materials/',
  path: '/materials/',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialTypesIndexRoute = MaterialTypesIndexRouteImport.update({
  id: '/material-types/',
  path: '/material-types/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManufacturersIndexRoute = ManufacturersIndexRouteImport.update({
  id: '/manufacturers/',
  path: '/manufacturers/',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasesNewRoute = PurchasesNewRouteImport.update({
  id: '/purchases/new',
  path: '/purchases/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasesPurchaseIdRoute = PurchasesPurchaseIdRouteImport.update({
  id: '/purchases/$purchaseId',
  path: '/purchases/$purchaseId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductLabelProductIdRoute = ProductLabelProductIdRouteImport.update({
  id: '/product-label/$productId',
  path: '/product-label/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersNewRoute = OrdersNewRouteImport.update({
  id: '/orders/new',
  path: '/orders/new',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialsMaterialIdRoute = MaterialsMaterialIdRouteImport.update({
  id: '/materials/$materialId',
  path: '/materials/$materialId',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialLabelMaterialIdRoute = MaterialLabelMaterialIdRouteImport.update({
  id: '/material-label/$materialId',
  path: '/material-label/$materialId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/material-label/$materialId': typeof MaterialLabelMaterialIdRoute
  '/materials/$materialId': typeof MaterialsMaterialIdRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/orders/new': typeof OrdersNewRoute
  '/product-label/$productId': typeof ProductLabelProductIdRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/purchases/$purchaseId': typeof PurchasesPurchaseIdRoute
  '/purchases/new': typeof PurchasesNewRoute
  '/manufacturers/': typeof ManufacturersIndexRoute
  '/material-types/': typeof MaterialTypesIndexRoute
  '/materials/': typeof MaterialsIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/purchases/': typeof PurchasesIndexRoute
  '/suppliers/': typeof SuppliersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/material-label/$materialId': typeof MaterialLabelMaterialIdRoute
  '/materials/$materialId': typeof MaterialsMaterialIdRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/orders/new': typeof OrdersNewRoute
  '/product-label/$productId': typeof ProductLabelProductIdRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/purchases/$purchaseId': typeof PurchasesPurchaseIdRoute
  '/purchases/new': typeof PurchasesNewRoute
  '/manufacturers': typeof ManufacturersIndexRoute
  '/material-types': typeof MaterialTypesIndexRoute
  '/materials': typeof MaterialsIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/products': typeof ProductsIndexRoute
  '/purchases': typeof PurchasesIndexRoute
  '/suppliers': typeof SuppliersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/material-label/$materialId': typeof MaterialLabelMaterialIdRoute
  '/materials/$materialId': typeof MaterialsMaterialIdRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/orders/new': typeof OrdersNewRoute
  '/product-label/$productId': typeof ProductLabelProductIdRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/purchases/$purchaseId': typeof PurchasesPurchaseIdRoute
  '/purchases/new': typeof PurchasesNewRoute
  '/manufacturers/': typeof ManufacturersIndexRoute
  '/material-types/': typeof MaterialTypesIndexRoute
  '/materials/': typeof MaterialsIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/purchases/': typeof PurchasesIndexRoute
  '/suppliers/': typeof SuppliersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/material-label/$materialId'
    | '/materials/$materialId'
    | '/orders/$orderId'
    | '/orders/new'
    | '/product-label/$productId'
    | '/products/$productId'
    | '/purchases/$purchaseId'
    | '/purchases/new'
    | '/manufacturers/'
    | '/material-types/'
    | '/materials/'
    | '/orders/'
    | '/products/'
    | '/purchases/'
    | '/suppliers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/material-label/$materialId'
    | '/materials/$materialId'
    | '/orders/$orderId'
    | '/orders/new'
    | '/product-label/$productId'
    | '/products/$productId'
    | '/purchases/$purchaseId'
    | '/purchases/new'
    | '/manufacturers'
    | '/material-types'
    | '/materials'
    | '/orders'
    | '/products'
    | '/purchases'
    | '/suppliers'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/material-label/$materialId'
    | '/materials/$materialId'
    | '/orders/$orderId'
    | '/orders/new'
    | '/product-label/$productId'
    | '/products/$productId'
    | '/purchases/$purchaseId'
    | '/purchases/new'
    | '/manufacturers/'
    | '/material-types/'
    | '/materials/'
    | '/orders/'
    | '/products/'
    | '/purchases/'
    | '/suppliers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  MaterialLabelMaterialIdRoute: typeof MaterialLabelMaterialIdRoute
  MaterialsMaterialIdRoute: typeof MaterialsMaterialIdRoute
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
  OrdersNewRoute: typeof OrdersNewRoute
  ProductLabelProductIdRoute: typeof ProductLabelProductIdRoute
  ProductsProductIdRoute: typeof ProductsProductIdRoute
  PurchasesPurchaseIdRoute: typeof PurchasesPurchaseIdRoute
  PurchasesNewRoute: typeof PurchasesNewRoute
  ManufacturersIndexRoute: typeof ManufacturersIndexRoute
  MaterialTypesIndexRoute: typeof MaterialTypesIndexRoute
  MaterialsIndexRoute: typeof MaterialsIndexRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  PurchasesIndexRoute: typeof PurchasesIndexRoute
  SuppliersIndexRoute: typeof SuppliersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers/': {
      id: '/suppliers/'
      path: '/suppliers'
      fullPath: '/suppliers/'
      preLoaderRoute: typeof SuppliersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchases/': {
      id: '/purchases/'
      path: '/purchases'
      fullPath: '/purchases/'
      preLoaderRoute: typeof PurchasesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materials/': {
      id: '/materials/'
      path: '/materials'
      fullPath: '/materials/'
      preLoaderRoute: typeof MaterialsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/material-types/': {
      id: '/material-types/'
      path: '/material-types'
      fullPath: '/material-types/'
      preLoaderRoute: typeof MaterialTypesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manufacturers/': {
      id: '/manufacturers/'
      path: '/manufacturers'
      fullPath: '/manufacturers/'
      preLoaderRoute: typeof ManufacturersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchases/new': {
      id: '/purchases/new'
      path: '/purchases/new'
      fullPath: '/purchases/new'
      preLoaderRoute: typeof PurchasesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchases/$purchaseId': {
      id: '/purchases/$purchaseId'
      path: '/purchases/$purchaseId'
      fullPath: '/purchases/$purchaseId'
      preLoaderRoute: typeof PurchasesPurchaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product-label/$productId': {
      id: '/product-label/$productId'
      path: '/product-label/$productId'
      fullPath: '/product-label/$productId'
      preLoaderRoute: typeof ProductLabelProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/new': {
      id: '/orders/new'
      path: '/orders/new'
      fullPath: '/orders/new'
      preLoaderRoute: typeof OrdersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$orderId': {
      id: '/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materials/$materialId': {
      id: '/materials/$materialId'
      path: '/materials/$materialId'
      fullPath: '/materials/$materialId'
      preLoaderRoute: typeof MaterialsMaterialIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/material-label/$materialId': {
      id: '/material-label/$materialId'
      path: '/material-label/$materialId'
      fullPath: '/material-label/$materialId'
      preLoaderRoute: typeof MaterialLabelMaterialIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  MaterialLabelMaterialIdRoute: MaterialLabelMaterialIdRoute,
  MaterialsMaterialIdRoute: MaterialsMaterialIdRoute,
  OrdersOrderIdRoute: OrdersOrderIdRoute,
  OrdersNewRoute: OrdersNewRoute,
  ProductLabelProductIdRoute: ProductLabelProductIdRoute,
  ProductsProductIdRoute: ProductsProductIdRoute,
  PurchasesPurchaseIdRoute: PurchasesPurchaseIdRoute,
  PurchasesNewRoute: PurchasesNewRoute,
  ManufacturersIndexRoute: ManufacturersIndexRoute,
  MaterialTypesIndexRoute: MaterialTypesIndexRoute,
  MaterialsIndexRoute: MaterialsIndexRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  PurchasesIndexRoute: PurchasesIndexRoute,
  SuppliersIndexRoute: SuppliersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
