/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StockTakesRouteRouteImport } from './routes/stock-takes/route'
import { Route as PurchasesRouteRouteImport } from './routes/purchases/route'
import { Route as ProductsRouteRouteImport } from './routes/products/route'
import { Route as OrdersRouteRouteImport } from './routes/orders/route'
import { Route as MaterialsRouteRouteImport } from './routes/materials/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuppliersIndexRouteImport } from './routes/suppliers/index'
import { Route as StockTakesIndexRouteImport } from './routes/stock-takes/index'
import { Route as PurchasesIndexRouteImport } from './routes/purchases/index'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as OrdersIndexRouteImport } from './routes/orders/index'
import { Route as MaterialsIndexRouteImport } from './routes/materials/index'
import { Route as MaterialTypesIndexRouteImport } from './routes/material-types/index'
import { Route as ManufacturersIndexRouteImport } from './routes/manufacturers/index'
import { Route as StockTakesUnresolvedRouteImport } from './routes/stock-takes/unresolved'
import { Route as StockTakesStockTakeIdRouteImport } from './routes/stock-takes/$stockTakeId'
import { Route as PurchasesNewRouteImport } from './routes/purchases/new'
import { Route as PurchasesPurchaseIdRouteImport } from './routes/purchases/$purchaseId'
import { Route as ProductsProductIdRouteImport } from './routes/products/$productId'
import { Route as ProductLabelProductIdRouteImport } from './routes/product-label.$productId'
import { Route as OrdersNewRouteImport } from './routes/orders/new'
import { Route as OrdersOrderIdRouteImport } from './routes/orders/$orderId'
import { Route as MaterialsMaterialIdRouteImport } from './routes/materials/$materialId'
import { Route as MaterialLabelMaterialIdRouteImport } from './routes/material-label.$materialId'
import { Route as DevBomPreviewRouteImport } from './routes/dev.bom-preview'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StockTakesRouteRoute = StockTakesRouteRouteImport.update({
  id: '/stock-takes',
  path: '/stock-takes',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasesRouteRoute = PurchasesRouteRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRouteRoute = ProductsRouteRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRouteRoute = OrdersRouteRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialsRouteRoute = MaterialsRouteRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersIndexRoute = SuppliersIndexRouteImport.update({
  id: '/suppliers/',
  path: '/suppliers/',
  getParentRoute: () => rootRouteImport,
} as any)
const StockTakesIndexRoute = StockTakesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StockTakesRouteRoute,
} as any)
const PurchasesIndexRoute = PurchasesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PurchasesRouteRoute,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProductsRouteRoute,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrdersRouteRoute,
} as any)
const MaterialsIndexRoute = MaterialsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MaterialsRouteRoute,
} as any)
const MaterialTypesIndexRoute = MaterialTypesIndexRouteImport.update({
  id: '/material-types/',
  path: '/material-types/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManufacturersIndexRoute = ManufacturersIndexRouteImport.update({
  id: '/manufacturers/',
  path: '/manufacturers/',
  getParentRoute: () => rootRouteImport,
} as any)
const StockTakesUnresolvedRoute = StockTakesUnresolvedRouteImport.update({
  id: '/unresolved',
  path: '/unresolved',
  getParentRoute: () => StockTakesRouteRoute,
} as any)
const StockTakesStockTakeIdRoute = StockTakesStockTakeIdRouteImport.update({
  id: '/$stockTakeId',
  path: '/$stockTakeId',
  getParentRoute: () => StockTakesRouteRoute,
} as any)
const PurchasesNewRoute = PurchasesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => PurchasesRouteRoute,
} as any)
const PurchasesPurchaseIdRoute = PurchasesPurchaseIdRouteImport.update({
  id: '/$purchaseId',
  path: '/$purchaseId',
  getParentRoute: () => PurchasesRouteRoute,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/$productId',
  path: '/$productId',
  getParentRoute: () => ProductsRouteRoute,
} as any)
const ProductLabelProductIdRoute = ProductLabelProductIdRouteImport.update({
  id: '/product-label/$productId',
  path: '/product-label/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersNewRoute = OrdersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => OrdersRouteRoute,
} as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => OrdersRouteRoute,
} as any)
const MaterialsMaterialIdRoute = MaterialsMaterialIdRouteImport.update({
  id: '/$materialId',
  path: '/$materialId',
  getParentRoute: () => MaterialsRouteRoute,
} as any)
const MaterialLabelMaterialIdRoute = MaterialLabelMaterialIdRouteImport.update({
  id: '/material-label/$materialId',
  path: '/material-label/$materialId',
  getParentRoute: () => rootRouteImport,
} as any)
const DevBomPreviewRoute = DevBomPreviewRouteImport.update({
  id: '/dev/bom-preview',
  path: '/dev/bom-preview',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/materials': typeof MaterialsRouteRouteWithChildren
  '/orders': typeof OrdersRouteRouteWithChildren
  '/products': typeof ProductsRouteRouteWithChildren
  '/purchases': typeof PurchasesRouteRouteWithChildren
  '/stock-takes': typeof StockTakesRouteRouteWithChildren
  '/settings': typeof SettingsRoute
  '/dev/bom-preview': typeof DevBomPreviewRoute
  '/material-label/$materialId': typeof MaterialLabelMaterialIdRoute
  '/materials/$materialId': typeof MaterialsMaterialIdRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/orders/new': typeof OrdersNewRoute
  '/product-label/$productId': typeof ProductLabelProductIdRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/purchases/$purchaseId': typeof PurchasesPurchaseIdRoute
  '/purchases/new': typeof PurchasesNewRoute
  '/stock-takes/$stockTakeId': typeof StockTakesStockTakeIdRoute
  '/stock-takes/unresolved': typeof StockTakesUnresolvedRoute
  '/manufacturers/': typeof ManufacturersIndexRoute
  '/material-types/': typeof MaterialTypesIndexRoute
  '/materials/': typeof MaterialsIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/purchases/': typeof PurchasesIndexRoute
  '/stock-takes/': typeof StockTakesIndexRoute
  '/suppliers/': typeof SuppliersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/dev/bom-preview': typeof DevBomPreviewRoute
  '/material-label/$materialId': typeof MaterialLabelMaterialIdRoute
  '/materials/$materialId': typeof MaterialsMaterialIdRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/orders/new': typeof OrdersNewRoute
  '/product-label/$productId': typeof ProductLabelProductIdRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/purchases/$purchaseId': typeof PurchasesPurchaseIdRoute
  '/purchases/new': typeof PurchasesNewRoute
  '/stock-takes/$stockTakeId': typeof StockTakesStockTakeIdRoute
  '/stock-takes/unresolved': typeof StockTakesUnresolvedRoute
  '/manufacturers': typeof ManufacturersIndexRoute
  '/material-types': typeof MaterialTypesIndexRoute
  '/materials': typeof MaterialsIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/products': typeof ProductsIndexRoute
  '/purchases': typeof PurchasesIndexRoute
  '/stock-takes': typeof StockTakesIndexRoute
  '/suppliers': typeof SuppliersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/materials': typeof MaterialsRouteRouteWithChildren
  '/orders': typeof OrdersRouteRouteWithChildren
  '/products': typeof ProductsRouteRouteWithChildren
  '/purchases': typeof PurchasesRouteRouteWithChildren
  '/stock-takes': typeof StockTakesRouteRouteWithChildren
  '/settings': typeof SettingsRoute
  '/dev/bom-preview': typeof DevBomPreviewRoute
  '/material-label/$materialId': typeof MaterialLabelMaterialIdRoute
  '/materials/$materialId': typeof MaterialsMaterialIdRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/orders/new': typeof OrdersNewRoute
  '/product-label/$productId': typeof ProductLabelProductIdRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/purchases/$purchaseId': typeof PurchasesPurchaseIdRoute
  '/purchases/new': typeof PurchasesNewRoute
  '/stock-takes/$stockTakeId': typeof StockTakesStockTakeIdRoute
  '/stock-takes/unresolved': typeof StockTakesUnresolvedRoute
  '/manufacturers/': typeof ManufacturersIndexRoute
  '/material-types/': typeof MaterialTypesIndexRoute
  '/materials/': typeof MaterialsIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/purchases/': typeof PurchasesIndexRoute
  '/stock-takes/': typeof StockTakesIndexRoute
  '/suppliers/': typeof SuppliersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/materials'
    | '/orders'
    | '/products'
    | '/purchases'
    | '/stock-takes'
    | '/settings'
    | '/dev/bom-preview'
    | '/material-label/$materialId'
    | '/materials/$materialId'
    | '/orders/$orderId'
    | '/orders/new'
    | '/product-label/$productId'
    | '/products/$productId'
    | '/purchases/$purchaseId'
    | '/purchases/new'
    | '/stock-takes/$stockTakeId'
    | '/stock-takes/unresolved'
    | '/manufacturers/'
    | '/material-types/'
    | '/materials/'
    | '/orders/'
    | '/products/'
    | '/purchases/'
    | '/stock-takes/'
    | '/suppliers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/dev/bom-preview'
    | '/material-label/$materialId'
    | '/materials/$materialId'
    | '/orders/$orderId'
    | '/orders/new'
    | '/product-label/$productId'
    | '/products/$productId'
    | '/purchases/$purchaseId'
    | '/purchases/new'
    | '/stock-takes/$stockTakeId'
    | '/stock-takes/unresolved'
    | '/manufacturers'
    | '/material-types'
    | '/materials'
    | '/orders'
    | '/products'
    | '/purchases'
    | '/stock-takes'
    | '/suppliers'
  id:
    | '__root__'
    | '/'
    | '/materials'
    | '/orders'
    | '/products'
    | '/purchases'
    | '/stock-takes'
    | '/settings'
    | '/dev/bom-preview'
    | '/material-label/$materialId'
    | '/materials/$materialId'
    | '/orders/$orderId'
    | '/orders/new'
    | '/product-label/$productId'
    | '/products/$productId'
    | '/purchases/$purchaseId'
    | '/purchases/new'
    | '/stock-takes/$stockTakeId'
    | '/stock-takes/unresolved'
    | '/manufacturers/'
    | '/material-types/'
    | '/materials/'
    | '/orders/'
    | '/products/'
    | '/purchases/'
    | '/stock-takes/'
    | '/suppliers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MaterialsRouteRoute: typeof MaterialsRouteRouteWithChildren
  OrdersRouteRoute: typeof OrdersRouteRouteWithChildren
  ProductsRouteRoute: typeof ProductsRouteRouteWithChildren
  PurchasesRouteRoute: typeof PurchasesRouteRouteWithChildren
  StockTakesRouteRoute: typeof StockTakesRouteRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  DevBomPreviewRoute: typeof DevBomPreviewRoute
  MaterialLabelMaterialIdRoute: typeof MaterialLabelMaterialIdRoute
  ProductLabelProductIdRoute: typeof ProductLabelProductIdRoute
  ManufacturersIndexRoute: typeof ManufacturersIndexRoute
  MaterialTypesIndexRoute: typeof MaterialTypesIndexRoute
  SuppliersIndexRoute: typeof SuppliersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock-takes': {
      id: '/stock-takes'
      path: '/stock-takes'
      fullPath: '/stock-takes'
      preLoaderRoute: typeof StockTakesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchases': {
      id: '/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof PurchasesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materials': {
      id: '/materials'
      path: '/materials'
      fullPath: '/materials'
      preLoaderRoute: typeof MaterialsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers/': {
      id: '/suppliers/'
      path: '/suppliers'
      fullPath: '/suppliers/'
      preLoaderRoute: typeof SuppliersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock-takes/': {
      id: '/stock-takes/'
      path: '/'
      fullPath: '/stock-takes/'
      preLoaderRoute: typeof StockTakesIndexRouteImport
      parentRoute: typeof StockTakesRouteRoute
    }
    '/purchases/': {
      id: '/purchases/'
      path: '/'
      fullPath: '/purchases/'
      preLoaderRoute: typeof PurchasesIndexRouteImport
      parentRoute: typeof PurchasesRouteRoute
    }
    '/products/': {
      id: '/products/'
      path: '/'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof ProductsRouteRoute
    }
    '/orders/': {
      id: '/orders/'
      path: '/'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof OrdersRouteRoute
    }
    '/materials/': {
      id: '/materials/'
      path: '/'
      fullPath: '/materials/'
      preLoaderRoute: typeof MaterialsIndexRouteImport
      parentRoute: typeof MaterialsRouteRoute
    }
    '/material-types/': {
      id: '/material-types/'
      path: '/material-types'
      fullPath: '/material-types/'
      preLoaderRoute: typeof MaterialTypesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manufacturers/': {
      id: '/manufacturers/'
      path: '/manufacturers'
      fullPath: '/manufacturers/'
      preLoaderRoute: typeof ManufacturersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock-takes/unresolved': {
      id: '/stock-takes/unresolved'
      path: '/unresolved'
      fullPath: '/stock-takes/unresolved'
      preLoaderRoute: typeof StockTakesUnresolvedRouteImport
      parentRoute: typeof StockTakesRouteRoute
    }
    '/stock-takes/$stockTakeId': {
      id: '/stock-takes/$stockTakeId'
      path: '/$stockTakeId'
      fullPath: '/stock-takes/$stockTakeId'
      preLoaderRoute: typeof StockTakesStockTakeIdRouteImport
      parentRoute: typeof StockTakesRouteRoute
    }
    '/purchases/new': {
      id: '/purchases/new'
      path: '/new'
      fullPath: '/purchases/new'
      preLoaderRoute: typeof PurchasesNewRouteImport
      parentRoute: typeof PurchasesRouteRoute
    }
    '/purchases/$purchaseId': {
      id: '/purchases/$purchaseId'
      path: '/$purchaseId'
      fullPath: '/purchases/$purchaseId'
      preLoaderRoute: typeof PurchasesPurchaseIdRouteImport
      parentRoute: typeof PurchasesRouteRoute
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof ProductsRouteRoute
    }
    '/product-label/$productId': {
      id: '/product-label/$productId'
      path: '/product-label/$productId'
      fullPath: '/product-label/$productId'
      preLoaderRoute: typeof ProductLabelProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/new': {
      id: '/orders/new'
      path: '/new'
      fullPath: '/orders/new'
      preLoaderRoute: typeof OrdersNewRouteImport
      parentRoute: typeof OrdersRouteRoute
    }
    '/orders/$orderId': {
      id: '/orders/$orderId'
      path: '/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof OrdersRouteRoute
    }
    '/materials/$materialId': {
      id: '/materials/$materialId'
      path: '/$materialId'
      fullPath: '/materials/$materialId'
      preLoaderRoute: typeof MaterialsMaterialIdRouteImport
      parentRoute: typeof MaterialsRouteRoute
    }
    '/material-label/$materialId': {
      id: '/material-label/$materialId'
      path: '/material-label/$materialId'
      fullPath: '/material-label/$materialId'
      preLoaderRoute: typeof MaterialLabelMaterialIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/bom-preview': {
      id: '/dev/bom-preview'
      path: '/dev/bom-preview'
      fullPath: '/dev/bom-preview'
      preLoaderRoute: typeof DevBomPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MaterialsRouteRouteChildren {
  MaterialsMaterialIdRoute: typeof MaterialsMaterialIdRoute
  MaterialsIndexRoute: typeof MaterialsIndexRoute
}

const MaterialsRouteRouteChildren: MaterialsRouteRouteChildren = {
  MaterialsMaterialIdRoute: MaterialsMaterialIdRoute,
  MaterialsIndexRoute: MaterialsIndexRoute,
}

const MaterialsRouteRouteWithChildren = MaterialsRouteRoute._addFileChildren(
  MaterialsRouteRouteChildren,
)

interface OrdersRouteRouteChildren {
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
  OrdersNewRoute: typeof OrdersNewRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
}

const OrdersRouteRouteChildren: OrdersRouteRouteChildren = {
  OrdersOrderIdRoute: OrdersOrderIdRoute,
  OrdersNewRoute: OrdersNewRoute,
  OrdersIndexRoute: OrdersIndexRoute,
}

const OrdersRouteRouteWithChildren = OrdersRouteRoute._addFileChildren(
  OrdersRouteRouteChildren,
)

interface ProductsRouteRouteChildren {
  ProductsProductIdRoute: typeof ProductsProductIdRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

const ProductsRouteRouteChildren: ProductsRouteRouteChildren = {
  ProductsProductIdRoute: ProductsProductIdRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}

const ProductsRouteRouteWithChildren = ProductsRouteRoute._addFileChildren(
  ProductsRouteRouteChildren,
)

interface PurchasesRouteRouteChildren {
  PurchasesPurchaseIdRoute: typeof PurchasesPurchaseIdRoute
  PurchasesNewRoute: typeof PurchasesNewRoute
  PurchasesIndexRoute: typeof PurchasesIndexRoute
}

const PurchasesRouteRouteChildren: PurchasesRouteRouteChildren = {
  PurchasesPurchaseIdRoute: PurchasesPurchaseIdRoute,
  PurchasesNewRoute: PurchasesNewRoute,
  PurchasesIndexRoute: PurchasesIndexRoute,
}

const PurchasesRouteRouteWithChildren = PurchasesRouteRoute._addFileChildren(
  PurchasesRouteRouteChildren,
)

interface StockTakesRouteRouteChildren {
  StockTakesStockTakeIdRoute: typeof StockTakesStockTakeIdRoute
  StockTakesUnresolvedRoute: typeof StockTakesUnresolvedRoute
  StockTakesIndexRoute: typeof StockTakesIndexRoute
}

const StockTakesRouteRouteChildren: StockTakesRouteRouteChildren = {
  StockTakesStockTakeIdRoute: StockTakesStockTakeIdRoute,
  StockTakesUnresolvedRoute: StockTakesUnresolvedRoute,
  StockTakesIndexRoute: StockTakesIndexRoute,
}

const StockTakesRouteRouteWithChildren = StockTakesRouteRoute._addFileChildren(
  StockTakesRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MaterialsRouteRoute: MaterialsRouteRouteWithChildren,
  OrdersRouteRoute: OrdersRouteRouteWithChildren,
  ProductsRouteRoute: ProductsRouteRouteWithChildren,
  PurchasesRouteRoute: PurchasesRouteRouteWithChildren,
  StockTakesRouteRoute: StockTakesRouteRouteWithChildren,
  SettingsRoute: SettingsRoute,
  DevBomPreviewRoute: DevBomPreviewRoute,
  MaterialLabelMaterialIdRoute: MaterialLabelMaterialIdRoute,
  ProductLabelProductIdRoute: ProductLabelProductIdRoute,
  ManufacturersIndexRoute: ManufacturersIndexRoute,
  MaterialTypesIndexRoute: MaterialTypesIndexRoute,
  SuppliersIndexRoute: SuppliersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
